[2024-06-05T21:56:28.592+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-05T21:56:28.619+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingestion_data.insertar_datos manual__2024-06-05T21:56:18.216641+00:00 [queued]>
[2024-06-05T21:56:28.634+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingestion_data.insertar_datos manual__2024-06-05T21:56:18.216641+00:00 [queued]>
[2024-06-05T21:56:28.635+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-05T21:56:28.656+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insertar_datos> on 2024-06-05 21:56:18.216641+00:00
[2024-06-05T21:56:28.664+0000] {standard_task_runner.py:63} INFO - Started process 1449 to run task
[2024-06-05T21:56:28.669+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ingestion_data', 'insertar_datos', 'manual__2024-06-05T21:56:18.216641+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/dag_entregable_fedebar.py', '--cfg-path', '/tmp/tmpy1d3q5fy']
[2024-06-05T21:56:28.671+0000] {standard_task_runner.py:91} INFO - Job 144: Subtask insertar_datos
[2024-06-05T21:56:28.734+0000] {task_command.py:426} INFO - Running <TaskInstance: ingestion_data.insertar_datos manual__2024-06-05T21:56:18.216641+00:00 [running]> on host 167cb9f6b96a
[2024-06-05T21:56:28.859+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FedeBar' AIRFLOW_CTX_DAG_ID='ingestion_data' AIRFLOW_CTX_TASK_ID='insertar_datos' AIRFLOW_CTX_EXECUTION_DATE='2024-06-05T21:56:18.216641+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-05T21:56:18.216641+00:00'
[2024-06-05T21:56:28.862+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-05T21:56:28.877+0000] {base.py:84} INFO - Using connection ID 'coder-redshift-fede' for task execution.
[2024-06-05T21:56:28.879+0000] {weather_info_ETL.py:23} INFO - Conectando a Redshift en data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com:5439/data-engineer-database
[2024-06-05T21:56:30.046+0000] {weather_info_ETL.py:32} INFO - Conectado a Redshift con éxito!
[2024-06-05T21:56:30.059+0000] {warnings.py:109} WARNING - /opt/***/dags/weather_info_ETL.py:167: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  existing_data = pd.read_sql(existing_data_query, conn)

[2024-06-05T21:56:30.879+0000] {warnings.py:109} WARNING - /opt/***/dags/weather_info_ETL.py:170: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  max_existing_load_date = pd.read_sql(max_existing_load_date_query, conn).iloc[0, 0]

[2024-06-05T21:56:46.736+0000] {weather_info_ETL.py:191} INFO - Datos insertados con éxito en la tabla daily_weather_3.
[2024-06-05T21:56:46.739+0000] {weather_info_ETL.py:200} INFO - Conexión a Redshift cerrada.
[2024-06-05T21:56:46.742+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-05T21:56:46.743+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-05T21:56:46.766+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ingestion_data, task_id=insertar_datos, run_id=manual__2024-06-05T21:56:18.216641+00:00, execution_date=20240605T215618, start_date=20240605T215628, end_date=20240605T215646
[2024-06-05T21:56:46.844+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-05T21:56:46.869+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-05T21:56:46.871+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
