[2024-05-29T21:12:30.695+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-29T21:12:30.717+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingestion_data.redshift_connection manual__2024-05-29T21:09:16.866581+00:00 [queued]>
[2024-05-29T21:12:30.726+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingestion_data.redshift_connection manual__2024-05-29T21:09:16.866581+00:00 [queued]>
[2024-05-29T21:12:30.728+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-05-29T21:12:30.740+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): redshift_connection> on 2024-05-29 21:09:16.866581+00:00
[2024-05-29T21:12:30.746+0000] {standard_task_runner.py:63} INFO - Started process 364 to run task
[2024-05-29T21:12:30.749+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ingestion_data', 'redshift_connection', 'manual__2024-05-29T21:09:16.866581+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/dag_entregable_fedebar.py', '--cfg-path', '/tmp/tmpwro1cts0']
[2024-05-29T21:12:30.751+0000] {standard_task_runner.py:91} INFO - Job 22: Subtask redshift_connection
[2024-05-29T21:12:30.801+0000] {task_command.py:426} INFO - Running <TaskInstance: ingestion_data.redshift_connection manual__2024-05-29T21:09:16.866581+00:00 [running]> on host 167cb9f6b96a
[2024-05-29T21:12:30.877+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FedeBar' AIRFLOW_CTX_DAG_ID='ingestion_data' AIRFLOW_CTX_TASK_ID='redshift_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-05-29T21:09:16.866581+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-29T21:09:16.866581+00:00'
[2024-05-29T21:12:30.879+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-29T21:12:30.888+0000] {base.py:84} INFO - Using connection ID 'coder-redshift-fede' for task execution.
[2024-05-29T21:12:30.889+0000] {logging_mixin.py:188} INFO - No es posible conectar a Redshift
[2024-05-29T21:12:30.897+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-29T21:12:30.906+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/weather_info_ETL.py", line 28, in conectar_redshift
    with conn.cursor() as cur:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/context.py", line 133, in __getattr__
    self.var = Connection.get_connection_from_secrets(key)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `cursor` isn't defined
[2024-05-29T21:12:30.915+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ingestion_data, task_id=redshift_connection, run_id=manual__2024-05-29T21:09:16.866581+00:00, execution_date=20240529T210916, start_date=20240529T211230, end_date=20240529T211230
[2024-05-29T21:12:30.926+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 22 for task redshift_connection (The conn_id `cursor` isn't defined; 364)
[2024-05-29T21:12:30.963+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-29T21:12:30.985+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-29T21:12:30.990+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
