[2024-05-27T21:18:05.734+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-27T21:18:06.021+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Preentrega3-fedebar.main scheduled__2024-05-21T03:00:00+00:00 [queued]>
[2024-05-27T21:18:06.172+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Preentrega3-fedebar.main scheduled__2024-05-21T03:00:00+00:00 [queued]>
[2024-05-27T21:18:06.190+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-27T21:18:06.346+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): main> on 2024-05-21 03:00:00+00:00
[2024-05-27T21:18:06.454+0000] {standard_task_runner.py:63} INFO - Started process 507 to run task
[2024-05-27T21:18:06.526+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Preentrega3-fedebar', 'main', 'scheduled__2024-05-21T03:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/dags_python_fedebar.py', '--cfg-path', '/tmp/tmp_e5e16bj']
[2024-05-27T21:18:06.588+0000] {standard_task_runner.py:91} INFO - Job 48: Subtask main
[2024-05-27T21:18:07.113+0000] {task_command.py:426} INFO - Running <TaskInstance: Preentrega3-fedebar.main scheduled__2024-05-21T03:00:00+00:00 [running]> on host ab7b4a79fe7d
[2024-05-27T21:18:08.992+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FedeBar' AIRFLOW_CTX_DAG_ID='Preentrega3-fedebar' AIRFLOW_CTX_TASK_ID='main' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-21T03:00:00+00:00'
[2024-05-27T21:18:09.015+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-27T21:18:09.032+0000] {logging_mixin.py:188} INFO - Inicio: 2024-05-27 21:18:09.032447
[2024-05-27T21:18:09.243+0000] {base.py:84} INFO - Using connection ID 'coder-redshift-fede' for task execution.
[2024-05-27T21:18:10.589+0000] {logging_mixin.py:188} INFO - Conectado a Redshift con Ã©xito!
[2024-05-27T21:18:11.152+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-27T21:18:11.154+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dags_python_fedebar.py", line 68, in main
    cache_session = requests_cache.CachedSession('.cache', expire_after = 3600)
NameError: name 'requests_cache' is not defined
[2024-05-27T21:18:11.204+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Preentrega3-fedebar, task_id=main, run_id=scheduled__2024-05-21T03:00:00+00:00, execution_date=20240521T030000, start_date=20240527T211806, end_date=20240527T211811
[2024-05-27T21:18:11.313+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 48 for task main (name 'requests_cache' is not defined; 507)
[2024-05-27T21:18:11.389+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-27T21:18:11.566+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-27T21:18:11.585+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
