[2024-05-28T18:29:09.066+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:29:09.075+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:29:09.094+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:29:09.092+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:29:09.143+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:29:09.135+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:29:09.146+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:29:09.213+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.215 seconds
[2024-05-28T18:29:39.495+0000] {processor.py:161} INFO - Started process (PID=112) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:29:39.498+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:29:39.501+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:29:39.500+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:29:39.522+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:29:39.516+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:29:39.524+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:29:39.563+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.081 seconds
[2024-05-28T18:30:10.004+0000] {processor.py:161} INFO - Started process (PID=182) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:30:10.005+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:30:10.007+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:30:10.007+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:30:10.023+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:30:10.018+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:30:10.025+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:30:10.049+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.052 seconds
[2024-05-28T18:30:40.408+0000] {processor.py:161} INFO - Started process (PID=252) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:30:40.410+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:30:40.415+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:30:40.415+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:30:40.429+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:30:40.426+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:30:40.430+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:30:40.450+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.050 seconds
[2024-05-28T18:31:10.989+0000] {processor.py:161} INFO - Started process (PID=330) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:31:10.991+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:31:10.993+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:31:10.992+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:31:11.004+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:31:11.002+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:31:11.005+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:31:11.022+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.039 seconds
[2024-05-28T18:31:41.303+0000] {processor.py:161} INFO - Started process (PID=399) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:31:41.305+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:31:41.306+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:31:41.306+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:31:41.318+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:31:41.315+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:31:41.320+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:31:41.339+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.044 seconds
[2024-05-28T18:32:11.792+0000] {processor.py:161} INFO - Started process (PID=469) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:32:11.793+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:32:11.796+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:32:11.796+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:32:11.823+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:32:11.812+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:32:11.825+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:32:11.879+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.100 seconds
[2024-05-28T18:32:42.170+0000] {processor.py:161} INFO - Started process (PID=539) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:32:42.171+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:32:42.173+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:32:42.173+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:32:42.186+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:32:42.183+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:32:42.187+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:32:42.206+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.042 seconds
[2024-05-28T18:33:12.492+0000] {processor.py:161} INFO - Started process (PID=616) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:33:12.493+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:33:12.495+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:33:12.495+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:33:12.506+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:33:12.504+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:33:12.508+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:33:12.524+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.038 seconds
[2024-05-28T18:33:42.984+0000] {processor.py:161} INFO - Started process (PID=686) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:33:42.989+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:33:42.992+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:33:42.991+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:33:43.010+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:33:43.006+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:33:43.012+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:33:43.044+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.073 seconds
[2024-05-28T18:34:13.143+0000] {processor.py:161} INFO - Started process (PID=764) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:34:13.144+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:34:13.147+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:34:13.147+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:34:13.167+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:34:13.163+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:34:13.169+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:34:13.192+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.059 seconds
[2024-05-28T18:34:43.535+0000] {processor.py:161} INFO - Started process (PID=834) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:34:43.536+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:34:43.538+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:34:43.537+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:34:43.549+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:34:43.547+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:34:43.550+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:34:43.569+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.039 seconds
[2024-05-28T18:35:14.264+0000] {processor.py:161} INFO - Started process (PID=904) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:35:14.265+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:35:14.267+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:35:14.267+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:35:14.279+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:35:14.276+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:35:14.280+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:35:14.299+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.041 seconds
[2024-05-28T18:35:44.673+0000] {processor.py:161} INFO - Started process (PID=982) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:35:44.674+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:35:44.676+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:35:44.676+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:35:44.687+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:35:44.684+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:35:44.689+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:35:44.714+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.048 seconds
[2024-05-28T18:36:14.949+0000] {processor.py:161} INFO - Started process (PID=1052) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:36:14.950+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:36:14.952+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:36:14.952+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:36:14.965+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:36:14.962+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:36:14.966+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:36:14.985+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.041 seconds
[2024-05-28T18:36:45.203+0000] {processor.py:161} INFO - Started process (PID=1122) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:36:45.204+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:36:45.206+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:36:45.205+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:36:45.218+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:36:45.215+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:36:45.219+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:36:45.238+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.042 seconds
[2024-05-28T18:37:15.453+0000] {processor.py:161} INFO - Started process (PID=1200) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:37:15.454+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:37:15.456+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:37:15.456+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:37:15.469+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:37:15.467+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:37:15.471+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:37:15.491+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.045 seconds
[2024-05-28T18:37:45.808+0000] {processor.py:161} INFO - Started process (PID=1271) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:37:45.809+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:37:45.811+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:37:45.811+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:37:45.826+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:37:45.823+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:37:45.827+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:37:45.847+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.045 seconds
[2024-05-28T18:38:16.093+0000] {processor.py:161} INFO - Started process (PID=1341) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:38:16.094+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:38:16.096+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:38:16.096+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:38:16.113+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:38:16.108+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:38:16.115+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:38:16.138+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.050 seconds
[2024-05-28T18:38:46.825+0000] {processor.py:161} INFO - Started process (PID=1419) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:38:46.826+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:38:46.828+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:38:46.828+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:38:46.841+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:38:46.838+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:38:46.842+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:38:46.860+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.042 seconds
[2024-05-28T18:39:17.340+0000] {processor.py:161} INFO - Started process (PID=1489) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:39:17.341+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:39:17.343+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:39:17.343+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:39:17.356+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:39:17.353+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:39:17.357+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:39:17.375+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.042 seconds
[2024-05-28T18:39:47.608+0000] {processor.py:161} INFO - Started process (PID=1559) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:39:47.609+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:39:47.611+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:39:47.611+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:39:47.628+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:39:47.624+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:39:47.630+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:39:47.652+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.052 seconds
[2024-05-28T18:40:18.226+0000] {processor.py:161} INFO - Started process (PID=1638) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:40:18.228+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:40:18.230+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:40:18.230+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:40:18.248+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:40:18.243+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:40:18.249+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:40:18.274+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.058 seconds
[2024-05-28T18:40:48.713+0000] {processor.py:161} INFO - Started process (PID=1708) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:40:48.714+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:40:48.716+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:40:48.716+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:40:48.727+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:40:48.725+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:40:48.729+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:40:48.749+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.044 seconds
[2024-05-28T18:41:19.094+0000] {processor.py:161} INFO - Started process (PID=1786) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:41:19.095+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:41:19.098+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:41:19.098+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:41:19.115+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:41:19.111+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:41:19.117+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:41:19.144+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.063 seconds
[2024-05-28T18:41:49.417+0000] {processor.py:161} INFO - Started process (PID=1855) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:41:49.418+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:41:49.421+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:41:49.420+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:41:49.441+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:41:49.437+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:41:49.443+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:41:49.465+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.055 seconds
[2024-05-28T18:42:19.743+0000] {processor.py:161} INFO - Started process (PID=1925) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:42:19.744+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:42:19.745+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:42:19.745+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:42:19.757+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:42:19.754+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:42:19.758+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:42:19.776+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.039 seconds
[2024-05-28T18:42:50.068+0000] {processor.py:161} INFO - Started process (PID=2003) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:42:50.069+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:42:50.071+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:42:50.070+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:42:50.083+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:42:50.080+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:42:50.084+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:42:50.102+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.041 seconds
[2024-05-28T18:43:20.463+0000] {processor.py:161} INFO - Started process (PID=2074) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:43:20.464+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:43:20.466+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:43:20.466+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:43:20.477+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:43:20.474+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:43:20.478+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:43:20.504+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.046 seconds
[2024-05-28T18:43:50.661+0000] {processor.py:161} INFO - Started process (PID=2152) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:43:50.662+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:43:50.664+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:43:50.664+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:43:50.680+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:43:50.677+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:43:50.681+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:43:50.702+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.048 seconds
[2024-05-28T18:44:21.098+0000] {processor.py:161} INFO - Started process (PID=2223) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:44:21.099+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:44:21.101+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:44:21.101+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:44:21.113+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:44:21.111+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:44:21.115+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:44:21.138+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.046 seconds
[2024-05-28T18:44:51.274+0000] {processor.py:161} INFO - Started process (PID=2298) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:44:51.275+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:44:51.277+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:44:51.277+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:44:51.291+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:44:51.288+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:44:51.292+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:44:51.310+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.042 seconds
[2024-05-28T18:45:21.519+0000] {processor.py:161} INFO - Started process (PID=2369) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:45:21.520+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:45:21.521+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:45:21.521+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:45:21.533+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:45:21.530+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:45:21.534+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:45:21.551+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.037 seconds
[2024-05-28T18:45:51.968+0000] {processor.py:161} INFO - Started process (PID=2439) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:45:51.969+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:45:51.971+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:45:51.971+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:45:51.985+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:45:51.982+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:45:51.986+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:45:52.007+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.043 seconds
[2024-05-28T18:46:22.405+0000] {processor.py:161} INFO - Started process (PID=2517) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:46:22.407+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:46:22.408+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:46:22.408+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:46:22.422+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:46:22.419+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:46:22.424+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:46:22.442+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.043 seconds
[2024-05-28T18:46:52.880+0000] {processor.py:161} INFO - Started process (PID=2587) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:46:52.881+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:46:52.883+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:46:52.883+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:46:52.893+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:46:52.890+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:46:52.894+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:46:52.911+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.037 seconds
[2024-05-28T18:47:23.263+0000] {processor.py:161} INFO - Started process (PID=2664) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:47:23.264+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:47:23.266+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:47:23.266+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:47:23.281+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:47:23.278+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:47:23.283+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:47:23.308+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.052 seconds
[2024-05-28T18:47:53.534+0000] {processor.py:161} INFO - Started process (PID=2735) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:47:53.535+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:47:53.537+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:47:53.536+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:47:53.547+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:47:53.545+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:47:53.549+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:47:53.566+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.038 seconds
[2024-05-28T18:48:23.843+0000] {processor.py:161} INFO - Started process (PID=2805) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:48:23.844+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:48:23.845+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:48:23.845+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:48:23.857+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:48:23.855+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:48:23.858+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:48:23.877+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.039 seconds
[2024-05-28T18:48:54.164+0000] {processor.py:161} INFO - Started process (PID=2883) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:48:54.166+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:48:54.167+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:48:54.167+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:48:54.179+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:48:54.176+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:48:54.180+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:48:54.198+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.040 seconds
[2024-05-28T18:49:24.842+0000] {processor.py:161} INFO - Started process (PID=2953) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:49:24.843+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:49:24.845+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:49:24.844+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:49:24.856+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:49:24.853+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:49:24.857+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:49:24.875+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.039 seconds
[2024-05-28T18:49:55.231+0000] {processor.py:161} INFO - Started process (PID=3031) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:49:55.232+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:49:55.234+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:49:55.234+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:49:55.246+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:49:55.243+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:49:55.247+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:49:55.264+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.040 seconds
[2024-05-28T18:50:25.651+0000] {processor.py:161} INFO - Started process (PID=3101) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:50:25.651+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:50:25.653+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:50:25.653+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:50:25.666+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:50:25.663+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:50:25.667+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:50:25.686+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.041 seconds
[2024-05-28T18:50:55.905+0000] {processor.py:161} INFO - Started process (PID=3180) to work on /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:50:55.907+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/weather_info_ETL.py for tasks to queue
[2024-05-28T18:50:55.909+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:50:55.908+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:50:55.922+0000] {logging_mixin.py:188} INFO - [2024-05-28T18:50:55.919+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/weather_info_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_info_ETL.py", line 1, in <module>
    import openmeteo_requests
ModuleNotFoundError: No module named 'openmeteo_requests'
[2024-05-28T18:50:55.923+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_info_ETL.py
[2024-05-28T18:50:55.945+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/weather_info_ETL.py took 0.046 seconds
