[2024-05-27T21:18:06.888+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-27T21:18:07.034+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Preentrega3-fedebar.main scheduled__2024-05-21T08:00:00+00:00 [queued]>
[2024-05-27T21:18:07.108+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Preentrega3-fedebar.main scheduled__2024-05-21T08:00:00+00:00 [queued]>
[2024-05-27T21:18:07.110+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-27T21:18:07.161+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): main> on 2024-05-21 08:00:00+00:00
[2024-05-27T21:18:07.253+0000] {standard_task_runner.py:63} INFO - Started process 508 to run task
[2024-05-27T21:18:07.314+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Preentrega3-fedebar', 'main', 'scheduled__2024-05-21T08:00:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/dags_python_fedebar.py', '--cfg-path', '/tmp/tmp1c20rlkq']
[2024-05-27T21:18:07.358+0000] {standard_task_runner.py:91} INFO - Job 49: Subtask main
[2024-05-27T21:18:08.688+0000] {task_command.py:426} INFO - Running <TaskInstance: Preentrega3-fedebar.main scheduled__2024-05-21T08:00:00+00:00 [running]> on host ab7b4a79fe7d
[2024-05-27T21:18:09.952+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FedeBar' AIRFLOW_CTX_DAG_ID='Preentrega3-fedebar' AIRFLOW_CTX_TASK_ID='main' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-21T08:00:00+00:00'
[2024-05-27T21:18:09.997+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-27T21:18:09.998+0000] {logging_mixin.py:188} INFO - Inicio: 2024-05-27 21:18:09.998406
[2024-05-27T21:18:10.048+0000] {base.py:84} INFO - Using connection ID 'coder-redshift-fede' for task execution.
[2024-05-27T21:18:11.284+0000] {logging_mixin.py:188} INFO - Conectado a Redshift con Ã©xito!
[2024-05-27T21:18:11.896+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-27T21:18:11.904+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dags_python_fedebar.py", line 68, in main
    cache_session = requests_cache.CachedSession('.cache', expire_after = 3600)
NameError: name 'requests_cache' is not defined
[2024-05-27T21:18:11.996+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Preentrega3-fedebar, task_id=main, run_id=scheduled__2024-05-21T08:00:00+00:00, execution_date=20240521T080000, start_date=20240527T211807, end_date=20240527T211811
[2024-05-27T21:18:12.100+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 49 for task main (name 'requests_cache' is not defined; 508)
[2024-05-27T21:18:12.168+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-27T21:18:12.259+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-27T21:18:12.270+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
