[2024-05-29T21:41:32.247+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-29T21:41:32.266+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingestion_data.redshift_connection manual__2024-05-29T21:41:27.044302+00:00 [queued]>
[2024-05-29T21:41:32.280+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingestion_data.redshift_connection manual__2024-05-29T21:41:27.044302+00:00 [queued]>
[2024-05-29T21:41:32.281+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-29T21:41:32.296+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): redshift_connection> on 2024-05-29 21:41:27.044302+00:00
[2024-05-29T21:41:32.304+0000] {standard_task_runner.py:63} INFO - Started process 1513 to run task
[2024-05-29T21:41:32.307+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ingestion_data', 'redshift_connection', 'manual__2024-05-29T21:41:27.044302+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/dag_entregable_fedebar.py', '--cfg-path', '/tmp/tmpvdr_hvm2']
[2024-05-29T21:41:32.309+0000] {standard_task_runner.py:91} INFO - Job 33: Subtask redshift_connection
[2024-05-29T21:41:32.359+0000] {task_command.py:426} INFO - Running <TaskInstance: ingestion_data.redshift_connection manual__2024-05-29T21:41:27.044302+00:00 [running]> on host 167cb9f6b96a
[2024-05-29T21:41:32.435+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FedeBar' AIRFLOW_CTX_DAG_ID='ingestion_data' AIRFLOW_CTX_TASK_ID='redshift_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-05-29T21:41:27.044302+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-29T21:41:27.044302+00:00'
[2024-05-29T21:41:32.437+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-29T21:41:32.446+0000] {base.py:84} INFO - Using connection ID 'coder-redshift-fede' for task execution.
[2024-05-29T21:41:32.447+0000] {weather_info_ETL.py:15} INFO - Conectando a Redshift en data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com:5439/data-engineer-database
[2024-05-29T21:41:33.617+0000] {weather_info_ETL.py:25} INFO - Conectado a Redshift con Ã©xito!
[2024-05-29T21:41:33.921+0000] {weather_info_ETL.py:63} ERROR - No es posible conectar a Redshift: no results to fetch
[2024-05-29T21:41:33.922+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-29T21:41:33.923+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-29T21:41:33.937+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ingestion_data, task_id=redshift_connection, run_id=manual__2024-05-29T21:41:27.044302+00:00, execution_date=20240529T214127, start_date=20240529T214132, end_date=20240529T214133
[2024-05-29T21:41:33.976+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-29T21:41:34.003+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-29T21:41:34.006+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
