[2024-05-21T01:08:17.705+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-21T01:08:17.872+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Preentrega3-fedebar.main scheduled__2024-05-20T17:00:00+00:00 [queued]>
[2024-05-21T01:08:17.921+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Preentrega3-fedebar.main scheduled__2024-05-20T17:00:00+00:00 [queued]>
[2024-05-21T01:08:17.927+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-05-21T01:08:18.006+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): main> on 2024-05-20 17:00:00+00:00
[2024-05-21T01:08:18.033+0000] {standard_task_runner.py:63} INFO - Started process 1000 to run task
[2024-05-21T01:08:18.054+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Preentrega3-fedebar', 'main', 'scheduled__2024-05-20T17:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/dags_python_fedebar.py', '--cfg-path', '/tmp/tmp9k9dceb2']
[2024-05-21T01:08:18.083+0000] {standard_task_runner.py:91} INFO - Job 22: Subtask main
[2024-05-21T01:08:18.335+0000] {task_command.py:426} INFO - Running <TaskInstance: Preentrega3-fedebar.main scheduled__2024-05-20T17:00:00+00:00 [running]> on host ab7b4a79fe7d
[2024-05-21T01:08:18.781+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FedeBar' AIRFLOW_CTX_DAG_ID='Preentrega3-fedebar' AIRFLOW_CTX_TASK_ID='main' AIRFLOW_CTX_EXECUTION_DATE='2024-05-20T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-20T17:00:00+00:00'
[2024-05-21T01:08:18.803+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-21T01:08:18.805+0000] {logging_mixin.py:188} INFO - Inicio: 2024-05-21 01:08:18.805059
[2024-05-21T01:08:18.810+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-21T01:08:18.812+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dags_python_fedebar.py", line 72, in main
    cache_session = requests_cache.CachedSession('.cache', expire_after = 3600)
NameError: name 'requests_cache' is not defined
[2024-05-21T01:08:18.850+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Preentrega3-fedebar, task_id=main, run_id=scheduled__2024-05-20T17:00:00+00:00, execution_date=20240520T170000, start_date=20240521T010817, end_date=20240521T010818
[2024-05-21T01:08:18.894+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 22 for task main (name 'requests_cache' is not defined; 1000)
[2024-05-21T01:08:18.939+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-21T01:08:19.005+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
