[2024-06-04T02:31:30.054+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-04T02:31:30.082+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingestion_data.insertar_datos manual__2024-06-04T02:31:18.725126+00:00 [queued]>
[2024-06-04T02:31:30.096+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingestion_data.insertar_datos manual__2024-06-04T02:31:18.725126+00:00 [queued]>
[2024-06-04T02:31:30.097+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-04T02:31:30.114+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insertar_datos> on 2024-06-04 02:31:18.725126+00:00
[2024-06-04T02:31:30.122+0000] {standard_task_runner.py:63} INFO - Started process 7101 to run task
[2024-06-04T02:31:30.125+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ingestion_data', 'insertar_datos', 'manual__2024-06-04T02:31:18.725126+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/dag_entregable_fedebar.py', '--cfg-path', '/tmp/tmp7wtp1_gh']
[2024-06-04T02:31:30.126+0000] {standard_task_runner.py:91} INFO - Job 102: Subtask insertar_datos
[2024-06-04T02:31:30.173+0000] {task_command.py:426} INFO - Running <TaskInstance: ingestion_data.insertar_datos manual__2024-06-04T02:31:18.725126+00:00 [running]> on host 167cb9f6b96a
[2024-06-04T02:31:30.311+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FedeBar' AIRFLOW_CTX_DAG_ID='ingestion_data' AIRFLOW_CTX_TASK_ID='insertar_datos' AIRFLOW_CTX_EXECUTION_DATE='2024-06-04T02:31:18.725126+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-04T02:31:18.725126+00:00'
[2024-06-04T02:31:30.325+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-04T02:31:30.342+0000] {base.py:84} INFO - Using connection ID 'coder-redshift-fede' for task execution.
[2024-06-04T02:31:30.343+0000] {weather_info_ETL.py:19} INFO - Conectando a Redshift en data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com:5439/data-engineer-database
[2024-06-04T02:31:31.582+0000] {warnings.py:109} WARNING - /opt/***/dags/weather_info_ETL.py:164: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  existing_data = pd.read_sql(existing_data_query, conn)

[2024-06-04T02:31:32.336+0000] {warnings.py:109} WARNING - /opt/***/dags/weather_info_ETL.py:167: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  max_existing_load_date = pd.read_sql(max_existing_load_date_query, conn).iloc[0, 0]

[2024-06-04T02:31:32.559+0000] {weather_info_ETL.py:193} ERROR - Error al insertar datos en Redshift: [Errno 2] No such file or directory: 'C:\\Fede\\Data Engineer Coderhouse\\Coder-entregable-3\x07irflow_docker\\poblacion.csv'
[2024-06-04T02:31:32.560+0000] {weather_info_ETL.py:196} INFO - Conexi√≥n a Redshift cerrada.
[2024-06-04T02:31:32.561+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-04T02:31:32.562+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-04T02:31:32.571+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ingestion_data, task_id=insertar_datos, run_id=manual__2024-06-04T02:31:18.725126+00:00, execution_date=20240604T023118, start_date=20240604T023130, end_date=20240604T023132
[2024-06-04T02:31:32.631+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-04T02:31:32.652+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-04T02:31:32.655+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
