[2024-06-03T23:05:19.428+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T23:05:19.465+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingestion_data.crear_tabla_si_no_existe scheduled__2024-06-02T00:00:00+00:00 [queued]>
[2024-06-03T23:05:19.477+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingestion_data.crear_tabla_si_no_existe scheduled__2024-06-02T00:00:00+00:00 [queued]>
[2024-06-03T23:05:19.480+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-03T23:05:19.513+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): crear_tabla_si_no_existe> on 2024-06-02 00:00:00+00:00
[2024-06-03T23:05:19.520+0000] {standard_task_runner.py:63} INFO - Started process 189 to run task
[2024-06-03T23:05:19.524+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ingestion_data', 'crear_tabla_si_no_existe', 'scheduled__2024-06-02T00:00:00+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/dag_entregable_fedebar.py', '--cfg-path', '/tmp/tmpsxnjioqe']
[2024-06-03T23:05:19.526+0000] {standard_task_runner.py:91} INFO - Job 56: Subtask crear_tabla_si_no_existe
[2024-06-03T23:05:19.593+0000] {task_command.py:426} INFO - Running <TaskInstance: ingestion_data.crear_tabla_si_no_existe scheduled__2024-06-02T00:00:00+00:00 [running]> on host 167cb9f6b96a
[2024-06-03T23:05:19.696+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FedeBar' AIRFLOW_CTX_DAG_ID='ingestion_data' AIRFLOW_CTX_TASK_ID='crear_tabla_si_no_existe' AIRFLOW_CTX_EXECUTION_DATE='2024-06-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-02T00:00:00+00:00'
[2024-06-03T23:05:19.699+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T23:05:19.715+0000] {base.py:84} INFO - Using connection ID 'coder-redshift-fede' for task execution.
[2024-06-03T23:05:19.716+0000] {weather_info_ETL.py:15} INFO - Conectando a Redshift en data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com:5439/data-engineer-database
[2024-06-03T23:05:21.365+0000] {logging_mixin.py:188} INFO - Conectado con Ã©xito a Redshift para crear tabla
[2024-06-03T23:05:21.759+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T23:05:21.763+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/weather_info_ETL.py", line 61, in crear_tabla_en_bd
    result = cur.fetchone()
psycopg2.ProgrammingError: no results to fetch
[2024-06-03T23:05:21.798+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ingestion_data, task_id=crear_tabla_si_no_existe, run_id=scheduled__2024-06-02T00:00:00+00:00, execution_date=20240602T000000, start_date=20240603T230519, end_date=20240603T230521
[2024-06-03T23:05:21.829+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 56 for task crear_tabla_si_no_existe (no results to fetch; 189)
[2024-06-03T23:05:21.879+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-03T23:05:21.915+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-03T23:05:21.920+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
