[2024-05-21T01:05:14.840+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-21T01:05:14.927+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Preentrega3-fedebar.main scheduled__2024-05-20T14:00:00+00:00 [queued]>
[2024-05-21T01:05:14.967+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Preentrega3-fedebar.main scheduled__2024-05-20T14:00:00+00:00 [queued]>
[2024-05-21T01:05:14.970+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-21T01:05:15.061+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): main> on 2024-05-20 14:00:00+00:00
[2024-05-21T01:05:15.084+0000] {standard_task_runner.py:63} INFO - Started process 856 to run task
[2024-05-21T01:05:15.090+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Preentrega3-fedebar', 'main', 'scheduled__2024-05-20T14:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dags_python_fedebar.py', '--cfg-path', '/tmp/tmporjnz9dh']
[2024-05-21T01:05:15.102+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask main
[2024-05-21T01:05:15.277+0000] {task_command.py:426} INFO - Running <TaskInstance: Preentrega3-fedebar.main scheduled__2024-05-20T14:00:00+00:00 [running]> on host ab7b4a79fe7d
[2024-05-21T01:05:15.801+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FedeBar' AIRFLOW_CTX_DAG_ID='Preentrega3-fedebar' AIRFLOW_CTX_TASK_ID='main' AIRFLOW_CTX_EXECUTION_DATE='2024-05-20T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-20T14:00:00+00:00'
[2024-05-21T01:05:15.817+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-21T01:05:15.828+0000] {logging_mixin.py:188} INFO - Inicio: 2024-05-21 01:05:15.827848
[2024-05-21T01:05:15.830+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-21T01:05:15.832+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dags_python_fedebar.py", line 72, in main
    cache_session = requests_cache.CachedSession('.cache', expire_after = 3600)
NameError: name 'requests_cache' is not defined
[2024-05-21T01:05:15.892+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Preentrega3-fedebar, task_id=main, run_id=scheduled__2024-05-20T14:00:00+00:00, execution_date=20240520T140000, start_date=20240521T010514, end_date=20240521T010515
[2024-05-21T01:05:15.945+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 14 for task main (name 'requests_cache' is not defined; 856)
[2024-05-21T01:05:15.992+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-21T01:05:16.022+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
