[2024-05-31T15:56:26.464+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-31T15:56:26.482+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingestion_data.crear_tabla_si_no_existe manual__2024-05-31T15:56:19.399505+00:00 [queued]>
[2024-05-31T15:56:26.491+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingestion_data.crear_tabla_si_no_existe manual__2024-05-31T15:56:19.399505+00:00 [queued]>
[2024-05-31T15:56:26.492+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-31T15:56:26.504+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): crear_tabla_si_no_existe> on 2024-05-31 15:56:19.399505+00:00
[2024-05-31T15:56:26.510+0000] {standard_task_runner.py:63} INFO - Started process 2892 to run task
[2024-05-31T15:56:26.513+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ingestion_data', 'crear_tabla_si_no_existe', 'manual__2024-05-31T15:56:19.399505+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/dag_entregable_fedebar.py', '--cfg-path', '/tmp/tmp_pwtllmv']
[2024-05-31T15:56:26.514+0000] {standard_task_runner.py:91} INFO - Job 50: Subtask crear_tabla_si_no_existe
[2024-05-31T15:56:26.599+0000] {task_command.py:426} INFO - Running <TaskInstance: ingestion_data.crear_tabla_si_no_existe manual__2024-05-31T15:56:19.399505+00:00 [running]> on host 167cb9f6b96a
[2024-05-31T15:56:26.867+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FedeBar' AIRFLOW_CTX_DAG_ID='ingestion_data' AIRFLOW_CTX_TASK_ID='crear_tabla_si_no_existe' AIRFLOW_CTX_EXECUTION_DATE='2024-05-31T15:56:19.399505+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-31T15:56:19.399505+00:00'
[2024-05-31T15:56:26.869+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-31T15:56:26.878+0000] {base.py:84} INFO - Using connection ID 'coder-redshift-fede' for task execution.
[2024-05-31T15:56:26.879+0000] {weather_info_ETL.py:15} INFO - Conectando a Redshift en data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com:5439/data-engineer-database
[2024-05-31T15:56:28.322+0000] {logging_mixin.py:188} INFO - Conectado con Ã©xito a Redshift para crear tabla
[2024-05-31T15:56:28.680+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-31T15:56:28.682+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/weather_info_ETL.py", line 61, in crear_tabla_en_bd
    result = cur.fetchone()
psycopg2.ProgrammingError: no results to fetch
[2024-05-31T15:56:28.696+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ingestion_data, task_id=crear_tabla_si_no_existe, run_id=manual__2024-05-31T15:56:19.399505+00:00, execution_date=20240531T155619, start_date=20240531T155626, end_date=20240531T155628
[2024-05-31T15:56:28.708+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 50 for task crear_tabla_si_no_existe (no results to fetch; 2892)
[2024-05-31T15:56:28.749+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-31T15:56:28.785+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-31T15:56:28.788+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
